### ISSUE TITLE
Websocket with 4 connexion 

### ISSUE THREAD

**Issue by Lyes37** [malliaridis/obssd#44]
Hi I'm looking for how to acces obs from a 4g connexion... I'm sure that there is some forwarding port settings... But I'm not sure

**Comment by malliaridis** [comment]
Accessing OBS from 4G can be achieved with a VPN or through a static IP address and port forwarding on your router. The problem you are facing here is that the OBS websocket plugin is not reachable from outside because your home network and router prevents direct access to your PC (for security reasons).

In order to reach your PC from outside the local area network you need to either "leak" your PC by making it accessible with port forwarding and by using a static IPv4 (which is normally only available for businesses), or join the same network with both devices by using a VPN (so your device gets through VPN into the same network).

There are solutions with proxies provided by the plugin in version 5.0, but those are still in beta and the OBSSD application is not compatible yet with the latest version.

_Sadly, I cannot provide you detailed instructions for the solutions above because those depend strongly on your setup._

**Comment by malliaridis** [comment]
Closing the ticket due to inactivity. If you have any further questions feel free to re-open it.
